name: Using Actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: A JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Micah
      - name: Log Time of Greeting
        run: echo "${{ steps.greet.outputs.time }}"

